# Generated by Django 4.2.7 on 2023-11-11 19:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='prayers',
        ),
        migrations.RemoveField(
            model_name='day',
            name='reflections',
        ),
        migrations.DeleteModel(
            name='Prayer',
        ),
        migrations.DeleteModel(
            name='Reflection',
        ),
        migrations.AddField(
            model_name='day',
            name='prayers',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='reflections',
            field=models.TextField(default=datetime.datetime(2023, 11, 11, 19, 9, 18, 395688, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
