# Generated by Django 4.2.7 on 2023-11-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_day_prayers_remove_day_reflections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='consecration',
        ),
    ]
